export const HOME_NEW_PATIENT_SECTION_CONSTANTS = {
  DEFAULT_MAIN_TITLE: 'Clinic Accessibility & Nearby Convenience',
  DEFAULT_ADDRESS_TITLE: '📍 Address',
  DEFAULT_ADDRESS_CONTENT: 'ClinSmile Dental Clinic <br>Ronak Residency, Plot No. 29, Roadpali <br> <br>Close to Kalamboli Bridge',
  DEFAULT_PARKING_TITLE: '🚗 Parking',
  DEFAULT_PARKING_CONTENT: 'Free parking available within our premises, with easy access for both two-wheelers and four-wheelers.',
  DEFAULT_TRANSIT_TITLE: '🚌 Public Transit',
  DEFAULT_TRANSIT_CONTENT: 'Connected by multiple city bus routes, with Roadpali Bus Stop just a few steps away.',
  DEFAULT_METRO_TITLE: '♿ Metro Access',
  DEFAULT_METRO_CONTENT: 'Walking distance from Kalamboli Bridge Metro Station, making it simple for daily commuters.',
  DEFAULT_ACCESSIBILITY_TITLE: '👨‍👩‍👧‍👦 Accessibility',
  DEFAULT_ACCESSIBILITY_CONTENT: 'Our clinic is designed to be family-friendly and wheelchair accessible, with a clean waiting area for kids and seniors.',
  DEFAULT_HOURS_TITLE: '⏰ Flexible Hours',
  DEFAULT_HOURS_CONTENT: 'Open late till 10:00 PM mon to sat, so you can schedule visits after office or school hours or on weekends.',
  DEFAULT_SAFETY_TITLE: '🛡️ Comfort & Safety',
  DEFAULT_SAFETY_CONTENT: 'A modern, hygienic setup equipped with advanced technology, ensuring a stress-free and safe dental experience.',
  DEFAULT_BUTTON_TEXT: 'Book Your Appointment',
  DEFAULT_MAP_TITLE: '📍 Visit Our Clinic',
  DEFAULT_LOCATION_TEXT: '📍 Location: Roadpali, Navi Mumbai, Maharashtra',
  DEFAULT_HOURS_TEXT: '🕒 Hours: Mon-Sat: 9:00 AM - 10:00 PM',
  DEFAULT_DIRECTIONS_TEXT: '📍 Get Directions',
  
  // Color constants - single source of truth
  DEFAULT_COLORS: {
    MAIN_TITLE: '#2c5aa0',
    ADDRESS_TITLE: '#2c5aa0',
    ADDRESS_CONTENT: '#333333',
    PARKING_TITLE: '#2c5aa0',
    PARKING_CONTENT: '#333333',
    TRANSIT_TITLE: '#2c5aa0',
    TRANSIT_CONTENT: '#333333',
    METRO_TITLE: '#2c5aa0',
    METRO_CONTENT: '#333333',
    ACCESSIBILITY_TITLE: '#2c5aa0',
    ACCESSIBILITY_CONTENT: '#333333',
    HOURS_TITLE: '#2c5aa0',
    HOURS_CONTENT: '#333333',
    SAFETY_TITLE: '#2c5aa0',
    SAFETY_CONTENT: '#333333',
    BUTTON_TEXT: '#ffffff',
    MAP_TITLE: '#2c5aa0',
    LOCATION_TEXT: '#333333',
    HOURS_TEXT: '#333333',
    DIRECTIONS_TEXT: '#2c5aa0',
    BACKGROUND: 'rgb(248,249,250)'
  },
  
  // Font family constants - single source of truth
  DEFAULT_FONTS: {
    MAIN_TITLE: 'Arial, sans-serif',
    ADDRESS_TITLE: 'Arial, sans-serif',
    ADDRESS_CONTENT: 'Arial, sans-serif',
    PARKING_TITLE: 'Arial, sans-serif',
    PARKING_CONTENT: 'Arial, sans-serif',
    TRANSIT_TITLE: 'Arial, sans-serif',
    TRANSIT_CONTENT: 'Arial, sans-serif',
    METRO_TITLE: 'Arial, sans-serif',
    METRO_CONTENT: 'Arial, sans-serif',
    ACCESSIBILITY_TITLE: 'Arial, sans-serif',
    ACCESSIBILITY_CONTENT: 'Arial, sans-serif',
    HOURS_TITLE: 'Arial, sans-serif',
    HOURS_CONTENT: 'Arial, sans-serif',
    SAFETY_TITLE: 'Arial, sans-serif',
    SAFETY_CONTENT: 'Arial, sans-serif',
    BUTTON_TEXT: 'Arial, sans-serif',
    MAP_TITLE: 'Arial, sans-serif',
    LOCATION_TEXT: 'Arial, sans-serif',
    HOURS_TEXT: 'Arial, sans-serif',
    DIRECTIONS_TEXT: 'Arial, sans-serif'
  }
} as const;
